# code: language=ansible
# Name: Griffin Pundt
# Date: 8/8/2024
---
# Installs necessary packages to host a PostgreSql database
- block:
    # apt update
  - name: apt update
    apt:
      name: '*'
      state: latest
      update_cache: yes
  rescue:
  - name: "[*] FAILED [*] apt update"
    ansible.builtin.debug:
      msg: "Error updating packages... skipping"

- block:
    # Install postgresql package to host SQL database
  - name: Install postgresql package
    apt:
      name: postgresql
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install postgresql package"
    ansible.builtin.debug:
      msg: "Error installing package... skipping"

- block:
    # Install additional packages to finalize database
  - name: Install additional packages (postgresql-contrib)
    apt:
      name: postgresql-contrib
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install additional packages (postgresql-contrib)"
    ansible.builtin.debug:
      msg: "Error installing package... skipping"