# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
# tasks file for /home/kali/Ansible/Infrastructure/database/roles/postgresql_ubuntu
- block:
  - import_tasks: install.yml
  - import_tasks: configure.yml
  - import_tasks: service.yml
    # Only executes tasks on debian-based boxes
    when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian") or
          (ansible-facts['distribution'] == "Kali")
