# code: language=ansible
# Name: Griffin Pundt
# Date: 8/8/2024
---
# Restarts postgresql
- block:
  - name: Restart and enable postgresql
    service: name=postgresql state=restarted enabled=yes
  rescue:
  - name: "[*] FAILED [*] Restart and enable postgresql... removing package"
    apt:
      name: postgresql
      state: absent