# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
- hosts: test
  become: yes
  gather_facts: yes
  become_method: sudo
  tasks:
    - name: Update rhel-based distributions
      block:
        - name: Install system updates for rhel-based distributions
          yum:
            name: "*"
            state: latest
            update_cache: yes
          when: (ansible_facts['distribution'] == "RedHat") or
                (ansible_facts['distribution'] == "CentOS") or
                (ansible_facts['distribution'] == "Rocky")
      rescue:
        - name: Print errors
          ansible.builtin.debug:
            msg: "Errors encountered... please debug"
    
    - name: Update Debian-based distributions
      block:
        - name: Install system updates on Debian-based distributions
          apt:
            name: '*'
            state: latest
            update_cache: yes
          when: (ansible_facts['distribution'] == "Debian") or
                (ansible_facts['distribution'] == "Ubuntu") or
                (ansible_facts['distribution'] == "Kali")
      rescue:
        - name: Print errors
          ansible.builtin.debug:
            msg: "Errors encountered... please debug"
  