# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
- name: Copy httpd Configuration file
  copy: src=files/httpd.conf dest=/etc/httpd/conf/httpd.conf

- name: Copy index.html file
  copy: src=files/index.html dest=/var/www/sammich/index.html
  notify:
  - restart apache