# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
- block:
      # yum update
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
  rescue:
    - name: "[*] FAILED [*] Update yum packages"
      ansible.builtin.debug:
        msg: "Error updating packages... skipping"

- block:
    # yum install httpd package to host the webserver
  - name: Install httpd Package
    yum: 
      name: httpd
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install httpd package"
    ansible.builtin.debug:
      msg: "Error installing httpd... skipping"