# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
- block:
  - name: Restart and enable httpd
    service: name=httpd state=restarted enabled=yes
  rescue:
    - name: "[*] FAILED [*] Restart and enable httpd... removing package"
      yum:
        name: httpd
        state: absent