---
# handlers file for /siem-stack/ansible/roles/configure-rsyslog-server

- name: restart systemd
  command: systemctl daemon-reload

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload firewall
  command: firewall-cmd --reload

- name: start vector
  service: name=vector.service state=restarted enabled=yes
