# Author: Griffin Pundt
# Date: 12/5/2023
# Notes: This task will copy all config files needed to receive and forward rsyslogs to aggregation server
---
- name: Copy rsyslog.conf to target
  copy: src=files/rsyslog.conf dest=/etc/rsyslog.conf

- name: Copy forwarding.conf to target
  copy: src=files/forwarding.conf dest=/etc/rsyslog.d/forwarding.conf

- name: Restart rsyslog
  service: name=rsyslog state=restarted enabled=yes
