---
# tasks file for /home/kali/Ansible/Infrastructure/jenkins/roles/jenkins_rhel
- block:
  - import_tasks: repository_update.yml
  - import_tasks: install.yml
  - import_tasks: firewall.yml
  - import_tasks: service.yml
    #Will only execute tasks on rhel-based-based distributions
    when: (ansible_facts['distribution'] == "RedHat") or
          (ansible_facts['distribution'] == "CentOS") or
          (ansible_facts['distribution'] == "Rocky")
