---
# tasks file for /home/kali/Ansible/Infrastructure/jenkins/roles/jenkins_ubuntu
- block:
  - import_tasks: repository_update.yml
  - import_tasks: install.yml
  - import_tasks: firewall.yml
  - import_tasks: service.yml
    #Will only execute tasks on Debian-based distributions
    when: (ansible_facts['distribution'] == "Debian") or
          (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Kali")
