# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
# This playbook will configure a PostgreSQL database on an Ubuntu Box
---
- hosts: localhost
  become: true
  become_user: root
  roles: 
    - postgresql_ubuntu