# code: language=ansible
# Name: Griffin Pundt
# Date: 8/7/2024
# This playbook will configure a Jenkins service on an debian-based Box
# Commands and guide found from digitalocean.com 
---
- hosts: test
  become: true
  become_user: root
  roles: 
    - jenkins_debian