# code: language=ansible
# Name: Griffin Pundt
# Date: 8/7/2024
# This playbook will configure a Jenkins service on an Ubuntu Box
---
- hosts: localhost
  become: true
  become_user: root
  roles: 
    - jenkins_ubuntu