# code: language=ansible
# Name: Griffin Pundt
# Date: 8/7/2024
---
- block:
  # allow port 8080 through firewall
  - name: UFW allow port 8080
    ufw:
      rule: allow
      port: '8080'
  rescue:
  - name: "[*] FAILED [*] UFW allow port 8080"
    ansible.builtin.debug:
      msg: "Failed allowing port 8080... skipping"
  
- block:
  # allow openssh through firewall
  - name: UFW allow openssh service
    ufw:
      rule: allow
      name: OpenSSH
  rescue:
  - name: "[*] FAILED [*] UFW allow openssh service"
    ansible.builtin.debug:
      msg: "Failed allowing openssh service... skipping"

- block:
  # enable firewall
  - name: Enable UFW
    ufw:
      state: enabled
  rescue:
  - name: "[*] FAILED [*] Enable UFW"
    ansible.builtin.debug:
      msg: "Failed enabling firewall... skipping"