# code: language=ansible
# Name: Griffin Pundt
# Date: 8/7/2024
---
- block:
  #Install Jenkins package
  - name: Install Jenkins package
    apt:
      name: jenkins
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install Jenkins package"
    ansible.builtin.debug:
      msg: "Error installing Jenkins... skipping"

- block:
  # Install UFW package
  - name: Install UFW package
    apt:
      name: ufw
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install UFW package"
    ansible.builtin.debug:
      msg: "Error installing ufw... skipping"