# code: language=ansible
# Name: Griffin Pundt
# Date: 8/8/2024
---
- block:
  # Install Java JDK
  - name: Install Java Development Kit
    yum:
      name: openjdk-17-jdk
      state: latest
  rescue:
    - name: "[*] FAILED [*] Install Java Development Kit"
      ansible.builtin.debug:
        msg: "Failed to install java... skipping"

- block:
  #Install Jenkins package
  - name: Install Jenkins package
    yum:
      name: jenkins
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install Jenkins package"
    ansible.builtin.debug:
      msg: "Error installing Jenkins... skipping"

- block:
  #Install Jenkins package
  - name: Install firewalld package
    yum:
      name: firewalld
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install firewalld package"
    ansible.builtin.debug:
      msg: "Error installing firewalld... skipping"