# code: language=ansible
# Name: Griffin Pundt
# Date: 8/5/2024
---
#Installs necessary packages to run the webserver
- block:
    #performs an apt update
  - name: Update apt packages
    apt:
      name: '*'
      state: latest
      update_cache: yes
  rescue:
  - name: "[*] FAILED [*] Update apt packages"
    ansible.builtin.debug:
      msg: "Error updating packages... skipping"

- block:
    # Installs programs to host a webserver
  - name: Install Apache package
    apt:
      name: apache2
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install Apache package"
    ansible.builtin.debug:
      msg: "Error installing apache... skipping"

- block:   
    # Installs Ubuntu firewall for remote connections
  - name: Install ufw firewall
    apt:
      name: ufw
      state: latest
  rescue:
  - name: "[*] FAILED [*] Install ufw firewall"
    ansible.builtin.debug: 
      msg: "Error installing ufw... skipping"
