# code: language=ansible
# Name: Griffin Pundt
# Date: 8/5/2024
---
# Main file to call all other tasks
- block:
  - import_tasks: install.yml
  - import_tasks: configure.yml
  - import_tasks: service.yml
    when: (ansible_facts['distribution'] == "Debian") or
          (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Kali")
