# code: language=ansible
# Name: Griffin Pundt
# Date: 8/5/2024
---
#Restarts apache
- block:
  - name: Restart and enable apache2
    service: name=apache2 state=restarted enabled=yes
  rescue:
  - name: "[*] FAILED [*] Restart and enable apache2... removing package"
    apt:
      name: apache2
      state: absent