# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
---
# Restarts postgresql
- block:
  - name: Restart and enable postgresql
    service: name=postgresql state=restarted enabled=yes
  rescue:
  - name: "[*] FAILED [*] Restart and enable postgresql"
    ansible.builtin.debug:
      msg: "Failed service restart... skipping"