# code: language=ansible
# Name: Griffin Pundt
# Date: 8/6/2024
# Purpose: This playbook will execute the Ansible Role to configure a rhel-based box for an apache webserver

---
- hosts: localhost
  become: true
  become_user: root
  roles: 
    - apache_rhel